services:
  - type: web
    name: acervo-teste
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /api/health
envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: postgresql://postgres.kewtadtuizlncqpphzcf:P*KD%2CQaC_bE8%40SH@aws-1-us-west-2.pooler.supabase.com:5432/postgres